// * CATEGORY*
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"
export const FIND_CATEGORY_BY_ID = "FIND_CATEGORY_BY_ID"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
// * USER*
export const CREATE_USER = "CREATE_USER"
export const FETCH_USER = "FETCH_CUSER"
export const EDIT_USER = "EDIT_USER"
export const FIND_USERBY_ID = "FIND_USER_BY_ID"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const DELETE_USER = "DELETE_USER"

// * PRODUCT*
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const FIND_PRODUCT_BY_ID = "FIND_PRODUCT_BY_ID"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
// *CART*
export const CREATE_CART = "CREATE_CART"
export const FETCH_CART = "FETCH_CART"
export const EDIT_CART = "EDIT_CART"
export const FIND_CART_BY_ID = "FIND_CART_BY_ID"